version: '3.9'

services:
  db:
    container_name: avangard-database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  app:
    container_name: avangard-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    ports:
      - "5000:5000"
    entrypoint: ["/code/entrypoint.sh"]
    volumes:
      - ./app:/app

volumes:
  postgres_data:
